#!/usr/bin/env bash

SCRIPTPATH="$(
	cd "$(dirname "$0")" || exit
	pwd -P
)"

export SCRIPTPATH

leftwm command "UnloadTheme"

# Kill Processes
pkill dunst
pkill polybar
pkill compton
pkill picom
pkill polybar
